import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lexer import Lexer
from parser import Parser


def generate_docs(source_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    dipjo_files = []
    for root, dirs, files in os.walk(source_dir):
        for f in files:
            if f.endswith(".dipjo"):
                dipjo_files.append(os.path.join(root, f))
    if not dipjo_files:
        print(f"No .dipjo files found in {source_dir}")
        return
    all_docs = []
    for filepath in sorted(dipjo_files):
        abs_path = os.path.abspath(filepath)
        with open(abs_path, "r", encoding="utf-8") as f:
            source = f.read()
        doc = {"file": filepath, "notes": [], "functions": [], "variables": []}
        lines = source.split("\n")
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("note "):
                note_text = stripped[5:].rstrip(".")
                doc["notes"].append(note_text)
            if stripped.startswith("define function"):
                parts = stripped.split()
                if len(parts) >= 3:
                    func_name = parts[2]
                    params = []
                    if "using" in parts:
                        idx = parts.index("using")
                        params = [p.rstrip(",") for p in parts[idx + 1:]]
                    doc["functions"].append({"name": func_name, "params": params})
        if doc["notes"] or doc["functions"]:
            all_docs.append(doc)
    readme_path = os.path.join(output_dir, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("# Project Documentation\n\n")
        f.write("Generated by `dipjo docs`.\n\n")
        for doc in all_docs:
            f.write(f"## {doc['file']}\n\n")
            if doc["notes"]:
                f.write("### Notes\n\n")
                for note in doc["notes"]:
                    f.write(f"- {note}\n")
                f.write("\n")
            if doc["functions"]:
                f.write("### Functions\n\n")
                for func in doc["functions"]:
                    params_str = ", ".join(func["params"]) if func["params"] else "none"
                    f.write(f"- **{func['name']}**({params_str})\n")
                f.write("\n")
    print(f"Documentation generated in {output_dir}")


if __name__ == "__main__":
    args = sys.argv[1:]
    source_dir = args[0] if len(args) > 0 else "."
    output_dir = args[1] if len(args) > 1 else "docs"
    generate_docs(source_dir, output_dir)
